
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnvtgxdnoenmgrxizmxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudnRneGRub2VubWdyeGl6bXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjE2NTMsImV4cCI6MjA2MjY5NzY1M30.Rf42XX_NmelbC2L7RGyky5--YFvlWELzRhFwckcuBdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'X-Client-Info': 'lovable-app'
    }
  }
});

// Test de la connexion au démarrage
console.log("=== INITIALISATION SUPABASE ===");
console.log("URL:", SUPABASE_URL);
console.log("Client créé:", !!supabase);

// Test de connexion simple
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.warn("Erreur lors de la vérification de session:", error);
  } else {
    console.log("Session actuelle:", data.session ? "Connecté" : "Non connecté");
  }
}).catch((err) => {
  console.error("Erreur lors du test de connexion:", err);
});
